'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const root = path.resolve(__dirname, '..');
const version = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')).version;

test('animal routes are generated by Astro as visible static profiles', () => {
    const source = fs.readFileSync(path.join(root, 'astro/src/pages/stats/[slug].astro'), 'utf8');
    const html = fs.readFileSync(path.join(root, 'stats/salamander.html'), 'utf8');

    assert.match(source, /getStaticPaths/);
    assert.match(source, /Scores are comparative editorial ratings/);
    assert.match(html, new RegExp(`<meta name="abs-version" content="${version.split('.').join('\\.')}"`));
    assert.match(html, /<h1 id="animal-title">Salamander<\/h1>/);
    assert.match(html, /COMBAT TELEMETRY/);
    assert.match(html, /TACTICAL READOUT/);
    assert.match(html, /href="\/stats#roster-title"/);
    assert.match(html, /type="application\/ld\+json"/);
    assert.match(html, /BreadcrumbList/);
    assert.doesNotMatch(html, /html\.js #seo-content/);
    assert.doesNotMatch(html, /<script[^>]+src=/);
    assert.doesNotMatch(html, /css\/legacy\.css/);
    assert.match(html, /<dt>Weight<\/dt><dd>0\.02 kg<\/dd>/);
});

test('Astro animal route retains responsive and reduced-motion design contracts', () => {
    const css = fs.readFileSync(path.join(root, 'css/pages/animal-static.css'), 'utf8');
    const shellCss = fs.readFileSync(path.join(root, 'css/static-shell.css'), 'utf8');
    const picture = fs.readFileSync(path.join(root, 'astro/src/components/AnimalPicture.astro'), 'utf8');

    assert.match(css, /@media \(max-width: 760px\)/);
    assert.match(shellCss, /@media \(prefers-reduced-motion: reduce\)/);
    assert.match(picture, /type="image\/avif"/);
    assert.match(picture, /type="image\/webp"/);
    assert.match(picture, /fetchpriority/);
    assert.match(picture, /width=\{image\.width\}/);
    assert.match(picture, /height=\{image\.height\}/);
});

test('About is a visible Astro methodology page with matching source and privacy claims', () => {
    const source = fs.readFileSync(path.join(root, 'astro/src/pages/about.astro'), 'utf8');
    const layout = fs.readFileSync(path.join(root, 'astro/src/layouts/SiteLayout.astro'), 'utf8');
    const html = fs.readFileSync(path.join(root, 'about.html'), 'utf8');

    assert.match(source, /What each battle stat means/);
    assert.match(source, /Per-field citation migration is in progress/);
    assert.match(source, /cartoons, generated animals, 3D renders, watermarked stock previews/);
    assert.match(html, /<h1 id="about-title">The rules behind the ratings\.<\/h1>/);
    assert.match(html, /Catalogue of Life/);
    assert.match(html, /IUCN Red List/);
    assert.match(html, /Animal Battle Stats comparative animal dataset/);
    assert.match(html, /mailto:animalbattlestats@gmail\.com/);
    assert.match(html, /type="application\/ld\+json"/);
    assert.doesNotMatch(html, /<script[^>]+src=/);
    assert.doesNotMatch(html, /css\/legacy\.css/);
    assert.match(layout, /css\/static-shell\.css/);
});

test('Stats directory is a crawlable Astro roster with lightweight discovery controls', () => {
    const source = fs.readFileSync(path.join(root, 'astro/src/pages/stats.astro'), 'utf8');
    const html = fs.readFileSync(path.join(root, 'stats.html'), 'utf8');
    const script = fs.readFileSync(path.join(root, 'js/stats-directory.js'), 'utf8');

    assert.match(source, /sourceRegistry\.entries/);
    assert.match(source, /Only reviewed real photographs with transparent backgrounds/);
    assert.match(source, /data-form-type="other"/);
    assert.match(source, /autocomplete="off"/);
    assert.equal((html.match(/class="roster-card"/g) || []).length, 225);
    assert.equal((html.match(/<picture/g) || []).length, 5);
    assert.match(html, /<h1 id="directory-title">Every animal\./);
    assert.match(html, /Animal Battle Stats directory/);
    assert.match(html, /\/js\/stats-directory\.js\?v=/);
    assert.doesNotMatch(html, /\/js\/main\.js/);
    assert.doesNotMatch(html, /css\/legacy\.css/);
    assert.match(script, /window\.location\.replace\(`\/stats\/\$\{legacySlug\}`\)/);
    assert.match(script, /history\.replaceState/);
    assert.match(script, /card\.hidden = !show/);
});
