// Animal data - synced from MongoDB on 2025-12-04T03:32:41.714Z
const animals = [
  {
    "name": "African Elephant",
    "image": "https://pngimg.com/uploads/elephants/elephants_PNG18776.png",
    "attack": 97.5,
    "defense": 98.9,
    "agility": 26,
    "stamina": 73.8,
    "intelligence": 95,
    "special": 21.3,
    "description": "The largest land animal on Earth, possessing immense raw strength and high intelligence. Their thick skin and massive size make them nearly invulnerable to most predators."
  },
  {
    "name": "African Lion",
    "image": "https://png.pngtree.com/png-clipart/20230507/ourmid/pngtree-big-lion-walking-wild-cat-png-image_7088507.png",
    "attack": 85.2,
    "defense": 68.8,
    "agility": 77.9,
    "stamina": 61,
    "intelligence": 56.5,
    "special": 81.5,
    "description": "The King of Beasts, known for its majestic mane and social pride structure. Males are built for fighting rivals, while females are expert cooperative hunters."
  },
  {
    "name": "African Wild Dog",
    "image": "https://static.vecteezy.com/system/resources/previews/068/743/693/non_2x/african-wild-dog-lycaon-pictus-isolated-on-transparent-background-endangered-painted-wolf-png.png",
    "attack": 55.4,
    "defense": 63.1,
    "agility": 81.3,
    "stamina": 99,
    "intelligence": 74.5,
    "special": 68,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Albatross",
    "image": "https://png.pngtree.com/png-vector/20240607/ourmid/pngtree-albatross-isolated-on-transparent-background-png-image_12622698.png",
    "attack": 10.8,
    "defense": 10.8,
    "agility": 55.9,
    "stamina": 89.9,
    "intelligence": 44,
    "special": 16,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Alligator",
    "image": "https://pngimg.com/d/crocodile_PNG13185.png",
    "attack": 91.4,
    "defense": 96.7,
    "agility": 11.6,
    "stamina": 55.7,
    "intelligence": 35.7,
    "special": 85,
    "description": "A Large creature found in Swamps, rivers, lakes."
  },
  {
    "name": "Alpaca",
    "image": "https://png.pngtree.com/png-vector/20250530/ourmid/pngtree-alpaca-isolated-on-a-transparent-background-png-image_16414654.png",
    "attack": 13.8,
    "defense": 23.7,
    "agility": 28,
    "stamina": 70.4,
    "intelligence": 40.8,
    "special": 11.3,
    "description": "A Small creature found in Mountains, grasslands."
  },
  {
    "name": "Anaconda",
    "image": "https://pngimg.com/uploads/anaconda/anaconda_PNG12.png",
    "attack": 83.4,
    "defense": 36.1,
    "agility": 10.6,
    "stamina": 40.9,
    "intelligence": 21.2,
    "special": 77,
    "description": "The heaviest snake in the world, a master of constriction. It coils around prey, suffocating them with immense pressure."
  },
  {
    "name": "Anglerfish",
    "image": "https://static.vecteezy.com/system/resources/previews/030/723/796/non_2x/angler-fish-isolated-on-a-transparent-background-free-png.png",
    "attack": 30.9,
    "defense": 27.7,
    "agility": 2,
    "stamina": 55.7,
    "intelligence": 30.7,
    "special": 26,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Anteater",
    "image": "https://png.pngtree.com/png-clipart/20250606/original/pngtree-walking-an-anteater-animal-png-image_21128272.png",
    "attack": 13.7,
    "defense": 5.8,
    "agility": 14.1,
    "stamina": 56.9,
    "intelligence": 47.9,
    "special": 27.9,
    "description": "A Medium creature found in Grasslands, forests."
  },
  {
    "name": "Arctic Fox",
    "image": "https://png.pngtree.com/png-clipart/20231008/original/pngtree-arctic-fox-transparent-background-png-image_13290621.png",
    "attack": 74.5,
    "defense": 56.6,
    "agility": 71.7,
    "stamina": 56.6,
    "intelligence": 76.6,
    "special": 23.1,
    "description": "A Tiny creature found in Arctic tundra."
  },
  {
    "name": "Arctic Wolf",
    "image": "https://png.pngtree.com/png-clipart/20240520/original/pngtree-an-arctic-wolf-transparent-background-png-image_15139629.png",
    "attack": 54.6,
    "defense": 62.6,
    "agility": 69,
    "stamina": 95.7,
    "intelligence": 81.3,
    "special": 72.6,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Armadillo",
    "image": "https://stickypng.com/wp-content/uploads/2023/07/5c7f956c72f5d9028c17ecb1.png",
    "attack": 10.7,
    "defense": 89.2,
    "agility": 6.8,
    "stamina": 59.8,
    "intelligence": 52.2,
    "special": 50,
    "description": "A Small creature found in Forests, grasslands."
  },
  {
    "name": "Army Ant",
    "image": "https://png.pngtree.com/png-clipart/20240731/original/pngtree-3d-army-ant-isolated-on-solid-transparent-background-ai-generative-png-image_15670375.png",
    "attack": 0.4,
    "defense": 5.5,
    "agility": 3.5,
    "stamina": 17.3,
    "intelligence": 10.8,
    "special": 55,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Axolotl",
    "image": "https://png.pngtree.com/png-vector/20240717/ourmid/pngtree-axolotl-on-white-background-png-image_13135659.png",
    "attack": 1.3,
    "defense": 1.3,
    "agility": 0.8,
    "stamina": 47.3,
    "intelligence": 27.3,
    "special": 27.3,
    "description": "A Tiny creature found in Lakes of Mexico City."
  },
  {
    "name": "Baboon",
    "image": "https://assets.stickpng.com/images/5af948f56554160a79bea0f3.png",
    "attack": 47.7,
    "defense": 55.9,
    "agility": 39.5,
    "stamina": 60.2,
    "intelligence": 87.5,
    "special": 41.9,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Bactrian Camel",
    "image": "https://parspng.com/wp-content/uploads/2024/02/camelpng.parspng.com-5.png",
    "attack": 73.6,
    "defense": 79.7,
    "agility": 15.4,
    "stamina": 99.8,
    "intelligence": 41,
    "special": 65,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Badger",
    "image": "https://upload.wikimedia.org/wikipedia/commons/6/66/Animals_png_set_by_mossi889-d4uye4q_-_Badger.png",
    "attack": 10.5,
    "defense": 43,
    "agility": 19.7,
    "stamina": 45.5,
    "intelligence": 60.3,
    "special": 70.2,
    "description": "A Small creature found in Forests, grasslands."
  },
  {
    "name": "Bald Eagle",
    "image": "https://www.nicepng.com/png/full/2-21156_bald-eagle-png-background-image-bald-eagle-transparent.png",
    "attack": 46.9,
    "defense": 23.4,
    "agility": 89.5,
    "stamina": 87.3,
    "intelligence": 73.6,
    "special": 73.6,
    "description": "A powerful raptor with a white head and tail. It uses massive talons to snatch fish and small mammals from the water or land."
  },
  {
    "name": "Barn Owl",
    "image": "https://static.vecteezy.com/system/resources/previews/043/988/968/non_2x/close-up-portrait-of-a-barn-owl-against-transparent-background-png.png",
    "attack": 46.2,
    "defense": 23.2,
    "agility": 63.4,
    "stamina": 82.7,
    "intelligence": 65,
    "special": 65,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Barracuda",
    "image": "https://png.pngtree.com/png-clipart/20250628/original/pngtree-barracuda-isolated-on-a-transparent-background-png-image_21240516.png",
    "attack": 30.3,
    "defense": 27.5,
    "agility": 76.6,
    "stamina": 49.3,
    "intelligence": 24.3,
    "special": 73,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Beaver",
    "image": "https://png.pngtree.com/png-vector/20240809/ourmid/pngtree-the-industrious-life-of-beavers-amazing-facts-about-png-image_13420997.png",
    "attack": 20.7,
    "defense": 10.6,
    "agility": 15.9,
    "stamina": 60.2,
    "intelligence": 71.4,
    "special": 30.2,
    "description": "A Small creature found in Rivers, lakes, streams."
  },
  {
    "name": "Beluga Whale",
    "image": "https://png.pngtree.com/png-vector/20240205/ourmid/pngtree-beluga-whale-sealife-png-image_11621534.png",
    "attack": 29.8,
    "defense": 88.4,
    "agility": 9.6,
    "stamina": 90.5,
    "intelligence": 81.9,
    "special": 45.9,
    "description": "A Large creature found in Arctic and sub-Arctic waters."
  },
  {
    "name": "Bighorn Sheep",
    "image": "https://static.vecteezy.com/system/resources/previews/054/590/008/non_2x/ram-with-big-horns-on-transparent-background-free-png.png",
    "attack": 13.6,
    "defense": 22.9,
    "agility": 61.4,
    "stamina": 56.8,
    "intelligence": 51.8,
    "special": 65,
    "description": "A Medium creature found in Mountains, cliffs."
  },
  {
    "name": "Bison",
    "image": "https://assets.stickpng.com/images/5a6f100aab538104d4a30e6d.png",
    "attack": 72.7,
    "defense": 87.6,
    "agility": 41.6,
    "stamina": 94.4,
    "intelligence": 50.1,
    "special": 80,
    "description": "The largest land mammal in North America. Massive heads and shoulder humps power their devastating charges."
  },
  {
    "name": "Black Bear",
    "image": "https://png.pngtree.com/png-vector/20240203/ourmid/pngtree-black-bear-cub-isolated-3d-rendering-png-image_11533156.png",
    "attack": 82.5,
    "defense": 83.7,
    "agility": 42.3,
    "stamina": 68.6,
    "intelligence": 40.7,
    "special": 76.9,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Black Mamba",
    "image": "https://png.pngtree.com/png-clipart/20241011/original/pngtree-a-beautiful-black-mamba-snake-reptile-on-transparent-png-image_16272393.png",
    "attack": 58.5,
    "defense": 35.5,
    "agility": 50.5,
    "stamina": 49.8,
    "intelligence": 33.1,
    "special": 97.5,
    "description": "A Small creature found in Savannas of Africa."
  },
  {
    "name": "Black Panther",
    "image": "https://png.pngtree.com/png-clipart/20231007/ourmid/pngtree-black-panther-in-ferocious-display-on-a-clear-transparent-background-png-image_10195947.png",
    "attack": 71.8,
    "defense": 68.3,
    "agility": 90.7,
    "stamina": 60.7,
    "intelligence": 56,
    "special": 79.5,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Black Rhinoceros",
    "image": "https://www.nicepng.com/png/full/278-2781004_rhinoceros-png-clip-art-black-rhinoceros-for-the.png",
    "attack": 95,
    "defense": 95.6,
    "agility": 12.1,
    "stamina": 79.8,
    "intelligence": 59.5,
    "special": 74.6,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Black Widow",
    "image": "https://png.pngtree.com/png-clipart/20241117/original/pngtree-black-widow-spider-clipart-illustration-high-quality-graphic-png-image_17160500.png",
    "attack": 13.4,
    "defense": 22.7,
    "agility": 21.2,
    "stamina": 56.1,
    "intelligence": 16.1,
    "special": 78,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Blue Whale",
    "image": "https://static.vecteezy.com/system/resources/previews/054/809/536/non_2x/blue-whale-isolated-on-the-transparent-background-marine-creature-free-png.png",
    "attack": 29.2,
    "defense": 92.2,
    "agility": 9.3,
    "stamina": 91.1,
    "intelligence": 71.2,
    "special": 31.6,
    "description": "The largest animal to ever exist. While peaceful filter feeders, their sheer bulk makes them virtually immune to predation as adults."
  },
  {
    "name": "Boa Constrictor",
    "image": "https://png.pngtree.com/png-clipart/20241011/original/pngtree-beautiful-boa-constrictor-snake-on-transparent-background-png-image_16272415.png",
    "attack": 81.6,
    "defense": 34.8,
    "agility": 10.3,
    "stamina": 42.1,
    "intelligence": 22.8,
    "special": 75,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Bobcat",
    "image": "https://png.pngtree.com/png-clipart/20241110/original/pngtree-view-of-wild-bobcat-transparent-background-png-image_16827981.png",
    "attack": 70.9,
    "defense": 55.2,
    "agility": 75.2,
    "stamina": 62.7,
    "intelligence": 59,
    "special": 73.2,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Bongo",
    "image": "https://png.pngtree.com/png-clipart/20241106/original/pngtree-transparent-bongo-cat-png-image_16691817.png",
    "attack": 10.4,
    "defense": 22.4,
    "agility": 19.4,
    "stamina": 78.4,
    "intelligence": 56.7,
    "special": 35.1,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Bottlenose Dolphin",
    "image": "https://png.pngtree.com/png-vector/20240531/ourmid/pngtree-playful-cartoon-blue-atlantic-bottlenose-dolphin-png-image_12579985.png",
    "attack": 28.6,
    "defense": 78.9,
    "agility": 75.9,
    "stamina": 87.2,
    "intelligence": 96.5,
    "special": 36.9,
    "description": "Highly intelligent marine mammals that use complex teamwork and echolocation. They can kill sharks by ramming their soft underbellies."
  },
  {
    "name": "Box Jellyfish",
    "image": "https://static.vecteezy.com/system/resources/previews/056/402/503/non_2x/box-jellyfish-isolated-on-a-transparent-background-png.png",
    "attack": 20.1,
    "defense": 27.2,
    "agility": 22.2,
    "stamina": 63.1,
    "intelligence": 57.1,
    "special": 100,
    "description": "One of the most venomous creatures on Earth. Its tentacles are covered in millions of explosive cells that deliver instant pain and death."
  },
  {
    "name": "Bull Shark",
    "image": "https://png.pngtree.com/png-clipart/20250417/original/pngtree-bull-shark-fish-isolated-on-transparent-background-png-image_20716697.png",
    "attack": 90.6,
    "defense": 27,
    "agility": 85.7,
    "stamina": 86.9,
    "intelligence": 27.6,
    "special": 82,
    "description": "A Large creature found in Coastal waters and rivers."
  },
  {
    "name": "Bullet Ant",
    "image": "https://static.vecteezy.com/system/resources/thumbnails/050/760/407/small/macro-photography-of-a-black-ant-on-a-transparent-background-png.png",
    "attack": 0.3,
    "defense": 5.3,
    "agility": 3.3,
    "stamina": 20.5,
    "intelligence": 13.4,
    "special": 90.5,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Bullfrog",
    "image": "https://png.pngtree.com/png-clipart/20240901/original/pngtree-bullfrog-sitting-png-image_15906776.png",
    "attack": 1.2,
    "defense": 1,
    "agility": 8.1,
    "stamina": 32.7,
    "intelligence": 12.7,
    "special": 14.1,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Camel",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/34/Transparent_Background_Dromedary_Camel.png",
    "attack": 70,
    "defense": 78.2,
    "agility": 15.1,
    "stamina": 100,
    "intelligence": 43.9,
    "special": 65,
    "description": "A Large creature found in Deserts."
  },
  {
    "name": "Camel Spider",
    "image": "https://upload.wikimedia.org/wikipedia/commons/7/78/Ammotrecha_itzaana_4414721993.png",
    "attack": 14.6,
    "defense": 77.4,
    "agility": 21.4,
    "stamina": 33.7,
    "intelligence": 24,
    "special": 65,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Cape Buffalo",
    "image": "https://static.vecteezy.com/system/resources/previews/066/397/223/non_2x/isolated-african-buffalo-image-in-format-on-transparent-background-for-editing-purposes-png.png",
    "attack": 92.3,
    "defense": 91.1,
    "agility": 29,
    "stamina": 76.8,
    "intelligence": 53.5,
    "special": 84,
    "description": "Known as 'The Black Death', these bovines are extremely aggressive and vengeful. Their fused horns form a bulletproof shield."
  },
  {
    "name": "Capuchin Monkey",
    "image": "https://static.vecteezy.com/system/resources/previews/048/947/305/non_2x/capuchin-monkey-on-a-transparent-background-png.png",
    "attack": 45.4,
    "defense": 54.5,
    "agility": 60,
    "stamina": 57.7,
    "intelligence": 93,
    "special": 47.7,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Capybara",
    "image": "https://png.pngtree.com/png-clipart/20250106/original/pngtree-capybara-isolated-on-transparent-background-png-image_20109760.png",
    "attack": 19.5,
    "defense": 10.3,
    "agility": 9.1,
    "stamina": 58.7,
    "intelligence": 68.7,
    "special": 26.6,
    "description": "A Medium creature found in South American wetlands."
  },
  {
    "name": "Caracal",
    "image": "https://png.pngtree.com/png-clipart/20250131/original/pngtree-caracal-isolated-on-transparent-background-png-image_20109761.png",
    "attack": 70,
    "defense": 53.9,
    "agility": 80,
    "stamina": 61.7,
    "intelligence": 57.5,
    "special": 75,
    "description": "A Medium creature found in Africa, Middle East, Central Asia."
  },
  {
    "name": "Cassowary",
    "image": "https://png.pngtree.com/png-clipart/20250306/original/pngtree-cassowary-bird-with-a-distinctive-helmet-like-crown-walking-in-its-png-image_20583525.png",
    "attack": 10.2,
    "defense": 28.7,
    "agility": 31.4,
    "stamina": 86.8,
    "intelligence": 57,
    "special": 85.5,
    "description": "Often called the world's most dangerous bird. It has a dagger-like claw on its foot capable of disemboweling predators."
  },
  {
    "name": "Chameleon",
    "image": "https://png.pngtree.com/png-clipart/20230506/original/pngtree-isolated-colorfull-chameleon-stand-on-branch-transparent-png-image_9145544.png",
    "attack": 10.1,
    "defense": 42.3,
    "agility": 13.9,
    "stamina": 48.9,
    "intelligence": 47.9,
    "special": 51.9,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Cheetah",
    "image": "https://png.pngtree.com/png-clipart/20231003/original/pngtree-cheetah-png-with-ai-generated-png-image_13245678.png",
    "attack": 69.2,
    "defense": 67.8,
    "agility": 98.2,
    "stamina": 47.1,
    "intelligence": 56.6,
    "special": 76.5,
    "description": "The fastest land animal, built purely for speed. It sacrifices strength and defense for the ability to run down any prey."
  },
  {
    "name": "Chimpanzee",
    "image": "https://pngimg.com/d/monkey_PNG18738.png",
    "attack": 44.6,
    "defense": 53.2,
    "agility": 49.8,
    "stamina": 62,
    "intelligence": 99,
    "special": 24,
    "description": "Our closest relatives, capable of extreme violence and coordinated warfare. They are fast, strong for their size, and use tools."
  },
  {
    "name": "Clouded Leopard",
    "image": "https://png.pngtree.com/png-vector/20250513/ourmid/pngtree-playful-white-clouded-leopard-cub-for-wildlife-graphics-png-image_16251416.png",
    "attack": 68.5,
    "defense": 67.2,
    "agility": 88.2,
    "stamina": 69.6,
    "intelligence": 69.4,
    "special": 78,
    "description": "A Medium creature found in Forests of Southeast Asia."
  },
  {
    "name": "Cockatoo",
    "image": "https://png.pngtree.com/png-clipart/20231110/original/pngtree-cockatoo-full-body-png-image_13524811.png",
    "attack": 10,
    "defense": 8.6,
    "agility": 47,
    "stamina": 65.9,
    "intelligence": 85,
    "special": 31.8,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Coconut Crab",
    "image": "https://png.pngtree.com/png-clipart/20241002/original/pngtree-crab-playing-with-coconut-png-image_16159600.png",
    "attack": 9.8,
    "defense": 22.2,
    "agility": 5.3,
    "stamina": 24.7,
    "intelligence": 16.8,
    "special": 56.8,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Colossal Squid",
    "image": "https://png.pngtree.com/png-vector/20220609/ourmid/pngtree-white-background-wordcard-design-featuring-a-giant-squid-vector-png-image_37153242.png",
    "attack": 53.8,
    "defense": 21.9,
    "agility": 16.1,
    "stamina": 45.7,
    "intelligence": 38.6,
    "special": 18.6,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Condor",
    "image": "https://static.vecteezy.com/system/resources/thumbnails/052/264/639/small_2x/front-view-andean-condor-is-spreading-its-wings-and-flying-isolated-on-a-transparent-background-png.png",
    "attack": 43.8,
    "defense": 21.7,
    "agility": 49.1,
    "stamina": 82.7,
    "intelligence": 65.1,
    "special": 65.1,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Cougar",
    "image": "https://static.vecteezy.com/system/resources/thumbnails/053/573/098/small/a-cougar-sitting-on-a-transparent-background-png.png",
    "attack": 67.7,
    "defense": 66.7,
    "agility": 83.2,
    "stamina": 62.4,
    "intelligence": 58.6,
    "special": 78,
    "description": "Also known as the mountain lion, it has the largest range of any land mammal in the Americas. It is a powerful jumper and silent stalker."
  },
  {
    "name": "Coyote",
    "image": "https://png.pngtree.com/png-vector/20240628/ourmid/pngtree-jackal-or-coyote-animal-on-a-transparent-background-png-image_12912471.png",
    "attack": 53.1,
    "defense": 62.1,
    "agility": 25,
    "stamina": 67.7,
    "intelligence": 74,
    "special": 67.7,
    "description": "A Small creature found in Grasslands, forests, deserts."
  },
  {
    "name": "Crow",
    "image": "https://pngimg.com/d/crow_PNG3094.png",
    "attack": 9.7,
    "defense": 8.3,
    "agility": 55.2,
    "stamina": 59.6,
    "intelligence": 94.5,
    "special": 19.2,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Cuttlefish",
    "image": "https://png.pngtree.com/png-vector/20240913/ourmid/pngtree-cuttlefish-side-view-transparent-background-png-image_13823624.png",
    "attack": 28.1,
    "defense": 26.7,
    "agility": 59.3,
    "stamina": 57.3,
    "intelligence": 91.5,
    "special": 68,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Deathstalker Scorpion",
    "image": "https://www.nicepng.com/png/full/26-261547_poisonous-scorpion-png-transparent-image-deathstalker-scorpion.png",
    "attack": 13.3,
    "defense": 5,
    "agility": 8.8,
    "stamina": 10.7,
    "intelligence": 5.6,
    "special": 93,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Dhole",
    "image": "https://png.pngtree.com/png-vector/20250204/ourmid/pngtree-dhole-also-known-as-the-asiatic-wild-dog-png-image_15384095.png",
    "attack": 52.3,
    "defense": 61.6,
    "agility": 24.7,
    "stamina": 96.5,
    "intelligence": 75.2,
    "special": 68.5,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Dingo",
    "image": "https://static.vecteezy.com/system/resources/previews/051/666/305/non_2x/dingo-side-view-isolated-on-transparent-background-png.png",
    "attack": 51.5,
    "defense": 61,
    "agility": 24.5,
    "stamina": 97,
    "intelligence": 72.9,
    "special": 66.9,
    "description": "A Small creature found in Deserts, forests, grasslands."
  },
  {
    "name": "Donkey",
    "image": "https://png.pngtree.com/png-vector/20250101/ourmid/pngtree-donkey-isolated-on-white-headstrong-farm-animal-with-domestic-mammal-look-png-image_14874365.png",
    "attack": 13.1,
    "defense": 21.4,
    "agility": 20.9,
    "stamina": 71.2,
    "intelligence": 42.4,
    "special": 13.6,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Dragonfly",
    "image": "https://png.pngtree.com/png-vector/20240129/ourmid/pngtree-dragonfly-png-with-ai-generated-png-image_11564530.png",
    "attack": 9.5,
    "defense": 41.6,
    "agility": 94.7,
    "stamina": 55.5,
    "intelligence": 45.8,
    "special": 17.9,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Electric Eel",
    "image": "https://png.pngtree.com/png-clipart/20250809/original/pngtree-electric-eel-isolated-on-a-transparent-background-png-image_21207328.png",
    "attack": 27.5,
    "defense": 26.5,
    "agility": 36.1,
    "stamina": 63.2,
    "intelligence": 38.2,
    "special": 92.5,
    "description": "Not a true eel, but a knifefish capable of generating 860 volts of electricity. It can stun prey or deter predators from a distance."
  },
  {
    "name": "Elk",
    "image": "https://png.pngtree.com/png-clipart/20241121/original/pngtree-elk-png-image_17283230.png",
    "attack": 19,
    "defense": 76.6,
    "agility": 62.1,
    "stamina": 94.7,
    "intelligence": 52.1,
    "special": 69.1,
    "description": "A Large creature found in Forests, mountains."
  },
  {
    "name": "Emperor Penguin",
    "image": "https://png.pngtree.com/png-clipart/20240514/original/pngtree-emperor-penguin-isolated-on-transparent-background-png-image_15084756.png",
    "attack": 13,
    "defense": 8.1,
    "agility": 7.3,
    "stamina": 61.2,
    "intelligence": 54.2,
    "special": 36.2,
    "description": "A Medium creature found in Antarctica."
  },
  {
    "name": "Emperor Scorpion",
    "image": "https://png.pngtree.com/png-clipart/20230912/original/pngtree-emperor-scorpion-white-background-picture-image_13031791.png",
    "attack": 12.8,
    "defense": 4.8,
    "agility": 7.1,
    "stamina": 34.9,
    "intelligence": 24.9,
    "special": 72,
    "description": "A Tiny creature found in Rainforests of West Africa."
  },
  {
    "name": "Emu",
    "image": "https://png.pngtree.com/png-vector/20250228/ourmid/pngtree-emu-bird-png-image_15612249.png",
    "attack": 12.7,
    "defense": 28.5,
    "agility": 33.4,
    "stamina": 85.6,
    "intelligence": 54.1,
    "special": 77,
    "description": "A Large creature found in Grasslands, forests."
  },
  {
    "name": "Fennec Fox",
    "image": "https://png.pngtree.com/png-clipart/20231008/original/pngtree-fennec-fox-transparent-background-png-image_13290629.png",
    "attack": 66.9,
    "defense": 52.5,
    "agility": 71,
    "stamina": 53.7,
    "intelligence": 73.7,
    "special": 17.4,
    "description": "A Tiny creature found in Deserts."
  },
  {
    "name": "Ferret",
    "image": "https://pngimg.com/uploads/ferret/ferret_PNG17112.png",
    "attack": 9.4,
    "defense": 40.9,
    "agility": 27.5,
    "stamina": 53.9,
    "intelligence": 63.9,
    "special": 72.6,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Flamingo",
    "image": "https://pngimg.com/d/flamingo_PNG15093.png",
    "attack": 12.5,
    "defense": 10.1,
    "agility": 20.7,
    "stamina": 59.6,
    "intelligence": 46.2,
    "special": 26.2,
    "description": "A Medium creature found in Lakes, lagoons."
  },
  {
    "name": "Flying Squirrel",
    "image": "https://png.pngtree.com/png-vector/20231114/ourmid/pngtree-sugarglider-flying-squirrel-png-image_10584524.png",
    "attack": 9.2,
    "defense": 4.5,
    "agility": 46.4,
    "stamina": 51.3,
    "intelligence": 64.7,
    "special": 21.3,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Gaboon Viper",
    "image": "https://png.pngtree.com/png-clipart/20250415/original/pngtree-high-quality-3d-gaboon-viper-snake-model-with-transparent-background-png-image_20683578.png",
    "attack": 57.7,
    "defense": 34.1,
    "agility": 6.3,
    "stamina": 45.7,
    "intelligence": 27.6,
    "special": 96,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Galapagos Tortoise",
    "image": "https://png.pngtree.com/png-clipart/20250518/original/pngtree-galapagos-giant-tortoise-on-transparent-background-png-image_21021132.png",
    "attack": 1,
    "defense": 90,
    "agility": 0.5,
    "stamina": 40.3,
    "intelligence": 15.3,
    "special": 40.3,
    "description": "A Large creature found in Galapagos Islands."
  },
  {
    "name": "Gazelle",
    "image": "https://www.pngmart.com/files/3/Gazelle-PNG-Transparent-Image.png",
    "attack": 18.4,
    "defense": 33.4,
    "agility": 92.9,
    "stamina": 74,
    "intelligence": 47.9,
    "special": 61.7,
    "description": "A Small creature found in Savannas, grasslands."
  },
  {
    "name": "Gecko",
    "image": "https://png.pngtree.com/png-vector/20250611/ourmid/pngtree-leopard-gecko-isolated-on-a-transparent-background-png-image_16518730.png",
    "attack": 9.1,
    "defense": 40.2,
    "agility": 30.7,
    "stamina": 43,
    "intelligence": 36,
    "special": 44,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Giant Centipede",
    "image": "https://pngimg.com/d/centipede_PNG2.png",
    "attack": 14.4,
    "defense": 4.3,
    "agility": 14.4,
    "stamina": 26.9,
    "intelligence": 18.5,
    "special": 70,
    "description": "A Tiny creature found in South American forests."
  },
  {
    "name": "Giant Squid",
    "image": "https://png.pngtree.com/png-clipart/20230814/original/pngtree-white-background-wordcard-design-featuring-a-giant-squid-vector-picture-image_10677754.png",
    "attack": 43.1,
    "defense": 4,
    "agility": 23.7,
    "stamina": 51.9,
    "intelligence": 47.8,
    "special": 27.8,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Gibbon",
    "image": "https://png.pngtree.com/png-clipart/20231005/ourmid/pngtree-hoolock-gibbon-transparent-background-png-image_10193781.png",
    "attack": 42.3,
    "defense": 51.8,
    "agility": 96.4,
    "stamina": 61.4,
    "intelligence": 88.5,
    "special": 43.5,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Gila Monster",
    "image": "https://png.pngtree.com/png-clipart/20230912/original/pngtree-gila-monster-looking-picture-image_13031491.png",
    "attack": 17.8,
    "defense": 39.5,
    "agility": 7.6,
    "stamina": 51,
    "intelligence": 52,
    "special": 87.5,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Giraffe",
    "image": "https://static.vecteezy.com/system/resources/previews/024/280/390/non_2x/giraffe-isolate-on-transparent-background-ai-generated-free-png.png",
    "attack": 8.9,
    "defense": 75.8,
    "agility": 30,
    "stamina": 73.4,
    "intelligence": 46.7,
    "special": 65,
    "description": "A Colossal creature found in Savannas, woodlands."
  },
  {
    "name": "Golden Eagle",
    "image": "https://static.vecteezy.com/system/resources/previews/047/554/734/non_2x/golden-eagle-isolated-on-transparent-background-free-png.png",
    "attack": 41.5,
    "defense": 21.2,
    "agility": 91.4,
    "stamina": 80.5,
    "intelligence": 61,
    "special": 61,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Goliath Birdeater",
    "image": "https://png.pngtree.com/png-clipart/20231101/original/pngtree-goliath-birdeater-colorful-endangered-photo-png-image_13482039.png",
    "attack": 14.3,
    "defense": 20.9,
    "agility": 2.8,
    "stamina": 21.2,
    "intelligence": 13.9,
    "special": 60,
    "description": "A Tiny creature found in Rainforests of South America."
  },
  {
    "name": "Goose",
    "image": "https://png.pngtree.com/png-vector/20231020/ourmid/pngtree-watercolor-goose-clip-art-png-image_10298313.png",
    "attack": 12.4,
    "defense": 9.8,
    "agility": 20.4,
    "stamina": 87.4,
    "intelligence": 58.5,
    "special": 38.5,
    "description": "A Small creature found in Wetlands, grasslands."
  },
  {
    "name": "Gorilla",
    "image": "https://pngimg.com/d/gorilla_PNG18709.png",
    "attack": 86.1,
    "defense": 51.1,
    "agility": 28.5,
    "stamina": 67,
    "intelligence": 97.5,
    "special": 34,
    "description": "A gentle giant until provoked, possessing immense upper body strength. Gorillas fight with crushing blows and powerful bites."
  },
  {
    "name": "Gray Wolf",
    "image": "https://png.pngtree.com/png-vector/20240512/ourmid/pngtree-a-lone-wolf-stands-amidst-vast-emptiness-silent-sentinel-in-world-png-image_12439843.png",
    "attack": 50.8,
    "defense": 60.5,
    "agility": 68.3,
    "stamina": 96,
    "intelligence": 77.7,
    "special": 70.2,
    "description": "The ultimate endurance hunter. Wolves use complex pack tactics to wear down prey much larger than themselves over long distances."
  },
  {
    "name": "Great Horned Owl",
    "image": "https://png.pngtree.com/png-clipart/20240722/original/pngtree-great-horned-owl-on-transparent-background-png-image_15609436.png",
    "attack": 40.8,
    "defense": 20.7,
    "agility": 67.6,
    "stamina": 87.6,
    "intelligence": 74.2,
    "special": 71.1,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Great White Shark",
    "image": "https://png.pngtree.com/png-clipart/20241110/original/pngtree-great-white-shark-transparent-background-png-image_16826884.png",
    "attack": 95,
    "defense": 26.2,
    "agility": 86.3,
    "stamina": 89.8,
    "intelligence": 39.1,
    "special": 85,
    "description": "The ultimate ocean predator, equipped with rows of serrated teeth and electromagnetic senses. It strikes from below with devastating force."
  },
  {
    "name": "Green Anaconda",
    "image": "https://static.vecteezy.com/system/resources/previews/059/466/540/non_2x/illustration-of-a-coiled-green-anaconda-with-spots-and-tongue-protruding-on-a-plain-background-transparent-background-free-png.png",
    "attack": 80.7,
    "defense": 32.7,
    "agility": 10.1,
    "stamina": 50.9,
    "intelligence": 34.5,
    "special": 78,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Grizzly Bear",
    "image": "https://png.pngtree.com/png-clipart/20240323/original/pngtree-grizzly-bear-png-png-image_14655347.png",
    "attack": 87,
    "defense": 84.5,
    "agility": 43,
    "stamina": 72.9,
    "intelligence": 53.6,
    "special": 80.3,
    "description": "A massive omnivore with bone-crushing jaws and paws that can kill a moose in a single swipe. Extremely durable and aggressive when provoked."
  },
  {
    "name": "Guanaco",
    "image": "https://static.vecteezy.com/system/resources/thumbnails/062/810/553/small/fluffy-guanaco-standing-profile-cut-out-transparent-png.png",
    "attack": 8.8,
    "defense": 20.4,
    "agility": 27.2,
    "stamina": 91.7,
    "intelligence": 46.9,
    "special": 20.3,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Hammerhead Shark",
    "image": "https://static.vecteezy.com/system/resources/previews/053/237/878/non_2x/hammerhead-shark-isolated-on-transparent-background-png.png",
    "attack": 84.3,
    "defense": 28.2,
    "agility": 83.8,
    "stamina": 88.1,
    "intelligence": 32.5,
    "special": 82.5,
    "description": "A Large creature found in Warm coastlines."
  },
  {
    "name": "Harpy Eagle",
    "image": "https://png.pngtree.com/png-vector/20240920/ourmid/pngtree-harpy-eagle-flying-with-transparent-background-png-image_13877939.png",
    "attack": 40,
    "defense": 20.2,
    "agility": 88.8,
    "stamina": 85.1,
    "intelligence": 69.5,
    "special": 69.5,
    "description": "The most powerful eagle in the Americas, with talons larger than a grizzly bear's claws. It hunts monkeys and sloths in the canopy."
  },
  {
    "name": "Hedgehog",
    "image": "https://static.vecteezy.com/system/resources/previews/048/720/340/non_2x/hedgehog-animal-isolated-on-transparent-background-free-png.png",
    "attack": 40,
    "defense": 75,
    "agility": 3,
    "stamina": 62.5,
    "intelligence": 73.1,
    "special": 55,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Hellbender",
    "image": "https://png.pngtree.com/png-vector/20250614/ourmid/pngtree-japanese-giant-salamander-isolated-on-a-transparent-background-png-image_16536523.png",
    "attack": 8.7,
    "defense": 0.8,
    "agility": 1.8,
    "stamina": 38.8,
    "intelligence": 18.8,
    "special": 23.2,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Hercules Beetle",
    "image": "https://png.pngtree.com/png-clipart/20250520/original/pngtree-png-hercules-beetle-vintage-insect-illustration-by-george-edwards-png-image_21035889.png",
    "attack": 12.3,
    "defense": 3.8,
    "agility": 2.5,
    "stamina": 27.6,
    "intelligence": 19.1,
    "special": 59.1,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Hippopotamus",
    "image": "https://png.pngtree.com/png-clipart/20230529/original/pngtree-hippo-isolated-on-transparent-background-png-image_9173057.png",
    "attack": 94.1,
    "defense": 93.3,
    "agility": 10.8,
    "stamina": 74.6,
    "intelligence": 49.3,
    "special": 84.5,
    "description": "One of the most aggressive animals on Earth. Despite being herbivorous, their massive jaws and tusks can snap a crocodile in half."
  },
  {
    "name": "Honey Badger",
    "image": "https://assets.stickpng.com/images/5c2e2b86a97bc40295eb8356.png",
    "attack": 8.5,
    "defense": 75,
    "agility": 45.7,
    "stamina": 55.1,
    "intelligence": 65.1,
    "special": 88.5,
    "description": "Notorious for its fearlessness and loose, thick skin. It will attack animals ten times its size and is immune to many venoms."
  },
  {
    "name": "Hornet",
    "image": "https://png.pngtree.com/png-clipart/20240520/original/pngtree-an-asian-giant-hornet-on-transparent-background-png-image_15139707.png",
    "attack": 12.1,
    "defense": 3.5,
    "agility": 32.7,
    "stamina": 17.1,
    "intelligence": 10.7,
    "special": 62,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Howler Monkey",
    "image": "https://png.pngtree.com/png-vector/20250601/ourmid/pngtree-monkey-isolated-on-a-transparent-background-png-image_16442751.png",
    "attack": 39.4,
    "defense": 50.5,
    "agility": 48.4,
    "stamina": 60.6,
    "intelligence": 41.2,
    "special": 42.5,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Hummingbird",
    "image": "https://png.pngtree.com/png-vector/20230903/ourmid/pngtree-hummingbird-colibri-png-image_9953519.png",
    "attack": 8.4,
    "defense": 7.8,
    "agility": 99.1,
    "stamina": 60.6,
    "intelligence": 53.5,
    "special": 33.5,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Huntsman Spider",
    "image": "https://static.vecteezy.com/system/resources/thumbnails/049/667/702/small/a-huntsman-spider-with-transparent-background-showing-its-eight-legs-and-three-eyes-on-a-black-background-png.png",
    "attack": 12,
    "defense": 3.3,
    "agility": 11.1,
    "stamina": 27.8,
    "intelligence": 19.3,
    "special": 69.3,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Hyena",
    "image": "https://png.pngtree.com/png-clipart/20220707/ourmid/pngtree-affrican-spotted-hyena-transparent-png-picture-png-image_5732585.png",
    "attack": 50,
    "defense": 60,
    "agility": 24.2,
    "stamina": 72.9,
    "intelligence": 89.5,
    "special": 75,
    "description": "Often misunderstood as scavengers, spotted hyenas are highly successful hunters with jaws that can crush bone."
  },
  {
    "name": "Ibex",
    "image": "https://png.pngtree.com/png-vector/20240819/ourmid/pngtree-a-image-of-ibex-png-image_13538242.png",
    "attack": 8.2,
    "defense": 19.9,
    "agility": 80,
    "stamina": 93.5,
    "intelligence": 57.6,
    "special": 70,
    "description": "A Medium creature found in Mountains, cliffs."
  },
  {
    "name": "Iguana",
    "image": "https://png.pngtree.com/png-vector/20250622/ourmid/pngtree-green-iguana-isolated-on-transparent-background-png-image_16570506.png",
    "attack": 8.1,
    "defense": 38.9,
    "agility": 13.6,
    "stamina": 41.1,
    "intelligence": 32.2,
    "special": 41.4,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Impala",
    "image": "https://png.pngtree.com/png-clipart/20231119/original/pngtree-adult-male-impala-isolated-africa-photo-png-image_13643700.png",
    "attack": 17.3,
    "defense": 32,
    "agility": 95.6,
    "stamina": 94.1,
    "intelligence": 47.3,
    "special": 61.2,
    "description": "A Small creature found in Savannas, woodlands."
  },
  {
    "name": "Jackal",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0a/Dogs%2C_jackals%2C_wolves%2C_and_foxes_BHL19827472_white_background.png",
    "attack": 49.2,
    "defense": 19.7,
    "agility": 23.9,
    "stamina": 69.1,
    "intelligence": 76.1,
    "special": 69.1,
    "description": "A Small creature found in Grasslands, deserts."
  },
  {
    "name": "Jaguar",
    "image": "https://pngimg.com/d/jaguar_PNG20746.png",
    "attack": 87,
    "defense": 66.2,
    "agility": 84.4,
    "stamina": 61.8,
    "intelligence": 57.7,
    "special": 80.5,
    "description": "The tank of the big cat world, with the strongest bite relative to size. It kills by piercing the skull or shell of its prey."
  },
  {
    "name": "Japanese Macaque",
    "image": "https://png.pngtree.com/png-vector/20250606/ourmid/pngtree-seated-japanese-macaque-png-image_16462905.png",
    "attack": 38.9,
    "defense": 49.8,
    "agility": 38.9,
    "stamina": 55,
    "intelligence": 86,
    "special": 35,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Kangaroo",
    "image": "https://static.vecteezy.com/system/resources/previews/023/839/454/non_2x/kangaroo-isolated-on-a-transparent-background-free-png.png",
    "attack": 7.9,
    "defense": 19.4,
    "agility": 73.8,
    "stamina": 75.1,
    "intelligence": 50.1,
    "special": 25.2,
    "description": "A Medium creature found in Grasslands, deserts."
  },
  {
    "name": "King Cobra",
    "image": "https://png.pngtree.com/png-clipart/20250703/original/pngtree-king-cobra-isolated-on-a-transparent-background-png-image_21231602.png",
    "attack": 56.9,
    "defense": 31.4,
    "agility": 25.2,
    "stamina": 50.8,
    "intelligence": 34.4,
    "special": 98.5,
    "description": "The longest venomous snake in the world. It feeds primarily on other snakes and delivers a massive dose of neurotoxin."
  },
  {
    "name": "King Crab",
    "image": "https://png.pngtree.com/png-vector/20240729/ourmid/pngtree-alaskan-king-crab-png-image_13272819.png",
    "attack": 7.8,
    "defense": 19.2,
    "agility": 5,
    "stamina": 58.1,
    "intelligence": 49.7,
    "special": 58.1,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Kiwi",
    "image": "https://pngimg.com/d/kiwi_bird_PNG10.png",
    "attack": 7.6,
    "defense": 7.6,
    "agility": 4.8,
    "stamina": 69.8,
    "intelligence": 59.8,
    "special": 39.8,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Koala",
    "image": "https://pngimg.com/d/koala_PNG114262.png",
    "attack": 7.5,
    "defense": 18.9,
    "agility": 4.5,
    "stamina": 27.3,
    "intelligence": 54.5,
    "special": 34.5,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Komodo Dragon",
    "image": "https://png.pngtree.com/png-clipart/20241011/original/pngtree-beautiful-komodo-dragon-on-transparent-background-png-image_16273109.png",
    "attack": 7.4,
    "defense": 82.9,
    "agility": 8.6,
    "stamina": 41.1,
    "intelligence": 75.8,
    "special": 91.5,
    "description": "The largest living lizard, a patient hunter with a venomous bite. It tracks wounded prey for miles until they succumb."
  },
  {
    "name": "Kookaburra",
    "image": "https://png.pngtree.com/png-vector/20240509/ourmid/pngtree-a-laughing-kookaburra-up-close-against-a-dark-green-png-image_12387079.png",
    "attack": 7.2,
    "defense": 7.3,
    "agility": 30,
    "stamina": 60.3,
    "intelligence": 47.1,
    "special": 73.5,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Kudu",
    "image": "https://png.pngtree.com/png-clipart/20240418/original/pngtree-greater-kudu-animal-character-png-image_14877772.png",
    "attack": 7.1,
    "defense": 30.7,
    "agility": 72.4,
    "stamina": 92.6,
    "intelligence": 40.7,
    "special": 11,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Leatherback Sea Turtle",
    "image": "https://png.pngtree.com/png-vector/20250618/ourmid/pngtree-leatherback-sea-turtle-isolated-on-a-transparent-background-png-image_16546811.png",
    "attack": 0.9,
    "defense": 90,
    "agility": 2.3,
    "stamina": 82.3,
    "intelligence": 16,
    "special": 41,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Leopard",
    "image": "https://pngimg.com/d/leopard_PNG14827.png",
    "attack": 66.2,
    "defense": 65.7,
    "agility": 90.1,
    "stamina": 66.5,
    "intelligence": 64.7,
    "special": 79.5,
    "description": "The most adaptable big cat, capable of hauling heavy prey up trees. They are masters of stealth and ambush."
  },
  {
    "name": "Lionfish",
    "image": "https://static.vecteezy.com/system/resources/previews/042/840/741/non_2x/lion-fish-on-transparent-background-png.png",
    "attack": 65.4,
    "defense": 65.2,
    "agility": 6.6,
    "stamina": 53,
    "intelligence": 28,
    "special": 80,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Llama",
    "image": "https://png.pngtree.com/png-clipart/20250528/original/pngtree-llama-isolated-on-a-transparent-background-png-image_21085769.png",
    "attack": 11.8,
    "defense": 18.7,
    "agility": 27.7,
    "stamina": 75.8,
    "intelligence": 51.5,
    "special": 27.3,
    "description": "A Medium creature found in Mountains, grasslands."
  },
  {
    "name": "Lobster",
    "image": "https://pngimg.com/d/lobster_PNG14234.png",
    "attack": 6.9,
    "defense": 18.4,
    "agility": 1.5,
    "stamina": 49.7,
    "intelligence": 37,
    "special": 49.7,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Lynx",
    "image": "https://pngimg.com/uploads/lynx/lynx_PNG3.png",
    "attack": 64.6,
    "defense": 49.1,
    "agility": 77.2,
    "stamina": 68.7,
    "intelligence": 68.1,
    "special": 76,
    "description": "A medium-sized cat with distinctive ear tufts and large paws that act as snowshoes. It is a specialist hunter of hares."
  },
  {
    "name": "Macaw",
    "image": "https://png.pngtree.com/png-clipart/20230429/ourmid/pngtree-isolated-scarlet-macaw-parrot-flying-on-transparent-png-image_6745591.png",
    "attack": 6.8,
    "defense": 7.1,
    "agility": 45,
    "stamina": 66.7,
    "intelligence": 84.5,
    "special": 33.4,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Magpie",
    "image": "https://static.vecteezy.com/system/resources/previews/054/572/793/non_2x/black-and-white-magpie-perched-attentively-isolated-on-transparent-background-free-png.png",
    "attack": 6.6,
    "defense": 6.8,
    "agility": 54.5,
    "stamina": 59.5,
    "intelligence": 85.5,
    "special": 18.9,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Manatee",
    "image": "https://png.pngtree.com/png-vector/20240717/ourmid/pngtree-manatee-on-a-transparent-background-png-image_13128953.png",
    "attack": 6.5,
    "defense": 74.5,
    "agility": 4.3,
    "stamina": 85.8,
    "intelligence": 80.9,
    "special": 44.5,
    "description": "A Large creature found in Coastal waters, rivers."
  },
  {
    "name": "Mandrill",
    "image": "https://png.pngtree.com/png-clipart/20250606/original/pngtree-mandrill-monkey-png-image_21132782.png",
    "attack": 6.3,
    "defense": 48.4,
    "agility": 43.6,
    "stamina": 57.7,
    "intelligence": 88,
    "special": 38.6,
    "description": "A Medium creature found in Rainforests of equatorial Africa."
  },
  {
    "name": "Maned Wolf",
    "image": "https://www.vhv.rs/dpng/d/477-4778323_transparent-wolf-png-maned-wolf-no-background-png.png",
    "attack": 48.5,
    "defense": 60,
    "agility": 60,
    "stamina": 73.3,
    "intelligence": 82.5,
    "special": 73.3,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Manta Ray",
    "image": "https://png.pngtree.com/png-clipart/20250714/original/pngtree-manta-ray-isolated-on-a-transparent-background-png-image_21296254.png",
    "attack": 26.9,
    "defense": 3,
    "agility": 66.2,
    "stamina": 88.5,
    "intelligence": 32.7,
    "special": 55.9,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Mantis Shrimp",
    "image": "https://png.pngtree.com/png-clipart/20231120/original/pngtree-mantis-shrimp-fresh-mantis-photo-png-image_13658294.png",
    "attack": 14.1,
    "defense": 2.8,
    "agility": 56.6,
    "stamina": 24.1,
    "intelligence": 16.3,
    "special": 92,
    "description": "A colorful crustacean with the fastest punch in the animal kingdom. Its strike boils the water and can crack aquarium glass."
  },
  {
    "name": "Marlin",
    "image": "https://png.pngtree.com/png-clipart/20240923/original/pngtree-beautiful-blue-marlin-on-transparent-background-png-image_16075083.png",
    "attack": 26.4,
    "defense": 26,
    "agility": 92,
    "stamina": 87.7,
    "intelligence": 28.3,
    "special": 50.4,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Meerkat",
    "image": "https://static.vecteezy.com/system/resources/previews/056/249/040/non_2x/meerkat-on-transparent-background-free-png.png",
    "attack": 6.2,
    "defense": 18.2,
    "agility": 19.2,
    "stamina": 52.4,
    "intelligence": 62.4,
    "special": 18.1,
    "description": "A Tiny creature found in Deserts, grasslands."
  },
  {
    "name": "Megalodon",
    "image": "https://png.pngtree.com/png-clipart/20231115/original/pngtree-megalodon-on-white-gigantic-picture-image_13263250.png",
    "attack": 100,
    "defense": 100,
    "agility": 60.7,
    "stamina": 56.7,
    "intelligence": 47.5,
    "special": 27.5,
    "description": "A Colossal creature found in Ancient Oceans."
  },
  {
    "name": "Monarch Butterfly",
    "image": "https://png.pngtree.com/png-clipart/20240819/original/pngtree-monarch-butterfly-transparent-png-image_15804597.png",
    "attack": 6.1,
    "defense": 2.5,
    "agility": 13.4,
    "stamina": 57.1,
    "intelligence": 48.2,
    "special": 19.1,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Mongoose",
    "image": "https://png.pngtree.com/png-vector/20241231/ourmid/pngtree-mongoose-image-png-image_15001548.png",
    "attack": 11.7,
    "defense": 38.2,
    "agility": 20.2,
    "stamina": 61.1,
    "intelligence": 71.1,
    "special": 29.9,
    "description": "A Tiny creature found in Forests, grasslands."
  },
  {
    "name": "Monitor Lizard",
    "image": "https://static.vecteezy.com/system/resources/previews/050/246/382/non_2x/monitor-lizard-illustration-on-transparent-background-free-png.png",
    "attack": 5.9,
    "defense": 37.5,
    "agility": 13.1,
    "stamina": 51.1,
    "intelligence": 80,
    "special": 54.8,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Moose",
    "image": "https://png.pngtree.com/png-vector/20230928/ourmid/pngtree-wild-moose-color-drawn-png-image_10149505.png",
    "attack": 63.8,
    "defense": 74,
    "agility": 40.9,
    "stamina": 95,
    "intelligence": 47.8,
    "special": 65.8,
    "description": "The largest species of deer, towering over most predators. Males grow massive antlers for fighting rivals and defending against wolves."
  },
  {
    "name": "Moray Eel",
    "image": "https://png.pngtree.com/png-clipart/20250704/original/pngtree-green-moray-eel-isolated-on-a-transparent-background-png-image_21220581.png",
    "attack": 25.8,
    "defense": 25.7,
    "agility": 14.9,
    "stamina": 49.7,
    "intelligence": 24.7,
    "special": 72,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Mountain Goat",
    "image": "https://png.pngtree.com/png-clipart/20240903/original/pngtree-mountain-goat-png-image_15925012.png",
    "attack": 11.5,
    "defense": 17.9,
    "agility": 80.6,
    "stamina": 93.2,
    "intelligence": 53.7,
    "special": 66.7,
    "description": "A Medium creature found in Mountains, cliffs."
  },
  {
    "name": "Musk Ox",
    "image": "https://assets.stickpng.com/images/5c822a2372f5d9028c17ed86.png",
    "attack": 63.1,
    "defense": 73.4,
    "agility": 25.5,
    "stamina": 91.4,
    "intelligence": 43.5,
    "special": 62.6,
    "description": "A Large creature found in Arctic tundra."
  },
  {
    "name": "Naked Mole Rat",
    "image": "https://png.pngtree.com/png-vector/20220706/ourmid/pngtree-cartoon-naked-mole-rat-smiling-png-image_5763603.png",
    "attack": 5.8,
    "defense": 9.6,
    "agility": 1.3,
    "stamina": 16.1,
    "intelligence": 61.1,
    "special": 12.1,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Narwhal",
    "image": "https://png.pngtree.com/png-clipart/20240831/original/pngtree-narwhal-illustration-png-image_15898276.png",
    "attack": 5.6,
    "defense": 72.9,
    "agility": 18.9,
    "stamina": 90.2,
    "intelligence": 79.1,
    "special": 28.2,
    "description": "A Large creature found in Arctic waters."
  },
  {
    "name": "Nautilus",
    "image": "https://png.pngtree.com/png-vector/20231015/ourmid/pngtree-nautilus-cartoon-shell-png-image_10164548.png",
    "attack": 5.5,
    "defense": 17.6,
    "agility": 1,
    "stamina": 45.1,
    "intelligence": 37.7,
    "special": 50.1,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Ocelot",
    "image": "https://png.pngtree.com/png-clipart/20241102/original/pngtree-cute-ocelot-isolated-on-white-background-png-image_16606654.png",
    "attack": 5.3,
    "defense": 47.7,
    "agility": 73.1,
    "stamina": 65.1,
    "intelligence": 62.6,
    "special": 73.5,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Octopus",
    "image": "https://png.pngtree.com/png-vector/20240207/ourmid/pngtree-octopus-sealife-animal-png-image_11711694.png",
    "attack": 5.2,
    "defense": 17.4,
    "agility": 65.5,
    "stamina": 53.1,
    "intelligence": 92,
    "special": 70,
    "description": "The most intelligent invertebrate. It can solve puzzles, change color and texture instantly, and squeeze through tiny gaps."
  },
  {
    "name": "Okapi",
    "image": "https://png.pngtree.com/png-vector/20240923/ourmid/pngtree-okapi-animal-on-transparent-background-png-image_13887806.png",
    "attack": 5,
    "defense": 17.1,
    "agility": 51.8,
    "stamina": 79.2,
    "intelligence": 58.5,
    "special": 37.7,
    "description": "A Large creature found in Rainforests of DR Congo."
  },
  {
    "name": "Opossum",
    "image": "https://png.pngtree.com/png-vector/20231019/ourmid/pngtree-possum-on-branch-png-image_10216004.png",
    "attack": 4.9,
    "defense": 16.9,
    "agility": 12.9,
    "stamina": 49.2,
    "intelligence": 63.2,
    "special": 19.2,
    "description": "A Small creature found in Forests, urban areas."
  },
  {
    "name": "Orangutan",
    "image": "https://pngimg.com/d/orangutan_PNG24.png",
    "attack": 38.3,
    "defense": 47,
    "agility": 23.4,
    "stamina": 58.1,
    "intelligence": 98.5,
    "special": 39.1,
    "description": "A Large creature found in Rainforests of Borneo and Sumatra."
  },
  {
    "name": "Orca",
    "image": "https://pngimg.com/d/killer_whale_PNG21.png",
    "attack": 98.8,
    "defense": 16.6,
    "agility": 26.2,
    "stamina": 87,
    "intelligence": 95.5,
    "special": 83,
    "description": "The apex predator of the ocean, combining immense size with pack intelligence. Orcas hunt everything from fish to blue whales."
  },
  {
    "name": "Oryx",
    "image": "https://png.pngtree.com/png-vector/20250210/ourmid/pngtree-arabian-oryx-in-format-with-transparent-background-1-png-image_15436437.png",
    "attack": 4.8,
    "defense": 30,
    "agility": 64.8,
    "stamina": 92.3,
    "intelligence": 44.5,
    "special": 16.7,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Osprey",
    "image": "https://png.pngtree.com/png-vector/20250319/ourmid/pngtree-realistic-osprey-perched-with-detailed-feathers-on-white-background-png-image_15767297.png",
    "attack": 37.7,
    "defense": 16.4,
    "agility": 86.9,
    "stamina": 83.1,
    "intelligence": 65.9,
    "special": 65.9,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Ostrich",
    "image": "https://pngimg.com/d/ostrich_PNG76983.png",
    "attack": 11.4,
    "defense": 28,
    "agility": 32,
    "stamina": 83.4,
    "intelligence": 48.6,
    "special": 74.3,
    "description": "A Large creature found in Savannas, deserts."
  },
  {
    "name": "Otter",
    "image": "https://png.pngtree.com/png-vector/20240805/ourmid/pngtree-charming-otter-wall-art-bringing-nature-png-image_13387007.png",
    "attack": 16.7,
    "defense": 59.3,
    "agility": 58.6,
    "stamina": 64.2,
    "intelligence": 74.4,
    "special": 60,
    "description": "A Small creature found in Rivers, coasts."
  },
  {
    "name": "Pangolin",
    "image": "https://png.pngtree.com/png-clipart/20231006/ourmid/pngtree-indian-pangolin-transparent-background-png-image_10194716.png",
    "attack": 4.6,
    "defense": 86.8,
    "agility": 4,
    "stamina": 58.8,
    "intelligence": 50.7,
    "special": 58,
    "description": "A Small creature found in Forests, grasslands."
  },
  {
    "name": "Peacock",
    "image": "https://png.pngtree.com/png-clipart/20231006/original/pngtree-elegant-peacock-bird---transparent-background-png-image_13280249.png",
    "attack": 4.5,
    "defense": 16.1,
    "agility": 15.6,
    "stamina": 61.2,
    "intelligence": 48.3,
    "special": 22.4,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Pelican",
    "image": "https://static.vecteezy.com/system/resources/thumbnails/068/620/176/small/pelican-open-mouth-isolated-transparency-background-large-bird-long-beak-standing-wildlife-detailed-feather-texture-expressive-nature-animal-side-view-png.png",
    "attack": 37.2,
    "defense": 9.3,
    "agility": 23.2,
    "stamina": 86.8,
    "intelligence": 56.9,
    "special": 36.9,
    "description": "A Medium creature found in Coasts, lakes, rivers."
  },
  {
    "name": "Peregrine Falcon",
    "image": "https://png.pngtree.com/png-vector/20250530/ourmid/pngtree-falcon-isolated-on-a-transparent-background-png-image_16424038.png",
    "attack": 36.6,
    "defense": 15.9,
    "agility": 100,
    "stamina": 82.9,
    "intelligence": 65.5,
    "special": 65.5,
    "description": "The fastest animal on the planet during its hunting stoop. It strikes birds in mid-air with the force of a bullet."
  },
  {
    "name": "Piranha",
    "image": "https://assets.stickpng.com/images/5baf5596554c7f08176ec069.png",
    "attack": 25.2,
    "defense": 25.5,
    "agility": 35.5,
    "stamina": 50.6,
    "intelligence": 25.6,
    "special": 73.5,
    "description": "A Tiny creature found in Rivers, floodplains."
  },
  {
    "name": "Platypus",
    "image": "https://purepng.com/public/uploads/large/platypus-on-the-ground-gw2.png",
    "attack": 16.1,
    "defense": 15.6,
    "agility": 21.9,
    "stamina": 61.4,
    "intelligence": 72.3,
    "special": 89,
    "description": "A Tiny creature found in Rivers, streams."
  },
  {
    "name": "Poison Dart Frog",
    "image": "https://static.vecteezy.com/system/resources/previews/056/947/472/non_2x/vibrant-blue-poison-dart-frog-isolated-on-transparent-background-free-png.png",
    "attack": 0.1,
    "defense": 0.5,
    "agility": 12.6,
    "stamina": 33.8,
    "intelligence": 13.8,
    "special": 94.5,
    "description": "A Tiny creature found in Rainforests of Central/South America."
  },
  {
    "name": "Polar Bear",
    "image": "https://pngimg.com/uploads/polar_bear/polar_bear_PNG14.png",
    "attack": 89.7,
    "defense": 86.1,
    "agility": 28.7,
    "stamina": 74.3,
    "intelligence": 57.8,
    "special": 81.4,
    "description": "The largest land carnivore, perfectly adapted to the frozen north. They are tireless swimmers and powerful hunters of seals."
  },
  {
    "name": "Porcupine",
    "image": "https://static.vecteezy.com/system/resources/previews/055/397/838/non_2x/porcupine-standing-with-quills-on-transparent-background-free-png.png",
    "attack": 14,
    "defense": 82.1,
    "agility": 5.8,
    "stamina": 56.6,
    "intelligence": 68.7,
    "special": 60,
    "description": "A Small creature found in Forests, grasslands."
  },
  {
    "name": "Praying Mantis",
    "image": "https://static.vecteezy.com/system/resources/previews/024/249/345/non_2x/praying-mantis-isolated-on-a-transparent-background-free-png.png",
    "attack": 24.7,
    "defense": 2.3,
    "agility": 22.4,
    "stamina": 49.5,
    "intelligence": 9.5,
    "special": 54.5,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Proboscis Monkey",
    "image": "https://png.pngtree.com/png-clipart/20250118/original/pngtree-proboscis-monkey-wildlife-vector-art-png-image_19781684.png",
    "attack": 36,
    "defense": 46.4,
    "agility": 47.7,
    "stamina": 68.8,
    "intelligence": 86.5,
    "special": 53.5,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Pronghorn",
    "image": "https://png.pngtree.com/png-vector/20250529/ourmid/pngtree-antelope-isolated-on-a-transparent-background-png-image_16406723.png",
    "attack": 15.6,
    "defense": 30,
    "agility": 97.3,
    "stamina": 98.5,
    "intelligence": 44.2,
    "special": 58.6,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Pufferfish",
    "image": "https://static.vecteezy.com/system/resources/previews/067/221/377/non_2x/pufferfish-on-a-transparent-background-free-png.png",
    "attack": 24.1,
    "defense": 25.2,
    "agility": 6.1,
    "stamina": 63.7,
    "intelligence": 38.7,
    "special": 95,
    "description": "A Small creature found in Tropical oceans."
  },
  {
    "name": "Puffin",
    "image": "https://assets.stickpng.com/images/5bc05f27dbc29e02dd82786c.png",
    "attack": 35.5,
    "defense": 6.6,
    "agility": 22.9,
    "stamina": 84.6,
    "intelligence": 51.5,
    "special": 31.5,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Python",
    "image": "https://static.vecteezy.com/system/resources/previews/047/828/387/non_2x/python-snake-on-transparent-background-free-png.png",
    "attack": 79.8,
    "defense": 29.7,
    "agility": 9.8,
    "stamina": 41.4,
    "intelligence": 21.9,
    "special": 74,
    "description": "A Large creature found in Rainforests, grasslands."
  },
  {
    "name": "Quokka",
    "image": "https://png.pngtree.com/png-vector/20250506/ourmid/pngtree-cute-quokka-standing-on-hind-legs-with-friendly-expression-png-image_16165978.png",
    "attack": 4.3,
    "defense": 15.4,
    "agility": 18.7,
    "stamina": 50.8,
    "intelligence": 31.7,
    "special": 16.1,
    "description": "A Small creature found in Islands of Western Australia."
  },
  {
    "name": "Quoll",
    "image": "https://cdn.pixabay.com/photo/2022/12/14/21/47/quoll-7656363_1280.png",
    "attack": 4.2,
    "defense": 15.1,
    "agility": 27,
    "stamina": 53.5,
    "intelligence": 37,
    "special": 17,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Raccoon",
    "image": "https://pngimg.com/d/raccoon_PNG16965.png",
    "attack": 4,
    "defense": 14.9,
    "agility": 18.4,
    "stamina": 52.2,
    "intelligence": 92.5,
    "special": 18,
    "description": "A Small creature found in Forests, urban areas."
  },
  {
    "name": "Rattlesnake",
    "image": "https://png.pngtree.com/png-vector/20231101/ourmid/pngtree-portrait-of-a-rattlesnake-animal-png-image_10387215.png",
    "attack": 56.2,
    "defense": 29.5,
    "agility": 7.8,
    "stamina": 42,
    "intelligence": 22.6,
    "special": 79,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Raven",
    "image": "https://static.vecteezy.com/system/resources/previews/060/054/534/non_2x/inspired-coastal-a-raven-common-raven-no-background-with-transparent-background-flawless-free-png.png",
    "attack": 3.9,
    "defense": 6.3,
    "agility": 53.9,
    "stamina": 64.2,
    "intelligence": 94,
    "special": 28.4,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Red Fox",
    "image": "https://png.pngtree.com/png-clipart/20241103/original/pngtree-a-beautiful-fox-on-transparent-background-png-image_16670328.png",
    "attack": 62.3,
    "defense": 45.7,
    "agility": 70.3,
    "stamina": 62,
    "intelligence": 82,
    "special": 34.1,
    "description": "A Small creature found in Forests, grasslands, urban."
  },
  {
    "name": "Red Panda",
    "image": "https://static.vecteezy.com/system/resources/previews/049/235/608/non_2x/red-panda-on-transparent-background-free-png.png",
    "attack": 3.8,
    "defense": 14.6,
    "agility": 26.7,
    "stamina": 52.7,
    "intelligence": 62.7,
    "special": 15.3,
    "description": "A Small creature found in Mountain forests."
  },
  {
    "name": "Red-Eyed Tree Frog",
    "image": "https://png.pngtree.com/png-clipart/20231017/original/pngtree-red-eyed-tree-frog-png-image_13339584.png",
    "attack": 0,
    "defense": 0.3,
    "agility": 16.9,
    "stamina": 33.6,
    "intelligence": 13.6,
    "special": 13.6,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Red-tailed Hawk",
    "image": "https://png.pngtree.com/png-clipart/20230914/original/pngtree-red-tailed-hawk-vector-png-image_12163349.png",
    "attack": 34.9,
    "defense": 14.4,
    "agility": 82.5,
    "stamina": 84.9,
    "intelligence": 69.3,
    "special": 69.3,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Reindeer",
    "image": "https://png.pngtree.com/png-clipart/20250420/original/pngtree-a-deer-isolated-with-transparent-background-png-image_20857866.png",
    "attack": 15,
    "defense": 29.2,
    "agility": 58,
    "stamina": 95.4,
    "intelligence": 55,
    "special": 67.7,
    "description": "A Medium creature found in Tundra, boreal forests."
  },
  {
    "name": "Reticulated Python",
    "image": "https://png.pngtree.com/png-clipart/20250620/original/pngtree-reticulated-python-isolated-on-a-transparent-background-png-image_21193785.png",
    "attack": 78.9,
    "defense": 29,
    "agility": 11.3,
    "stamina": 45,
    "intelligence": 26.6,
    "special": 76,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Rhinoceros",
    "image": "https://png.pngtree.com/png-vector/20240131/ourmid/pngtree-rhino-isolated-on-transparent-background-png-image_11636816.png",
    "attack": 93.2,
    "defense": 94.4,
    "agility": 11.8,
    "stamina": 72.7,
    "intelligence": 45.5,
    "special": 83,
    "description": "A prehistoric-looking tank with thick skin and a deadly horn. Rhinos are nearsighted but will charge anything that smells like a threat."
  },
  {
    "name": "Ring-tailed Lemur",
    "image": "https://static.vecteezy.com/system/resources/previews/046/437/488/non_2x/ring-tailed-lemur-side-view-isolated-on-transparent-background-free-png.png",
    "attack": 34.3,
    "defense": 45,
    "agility": 38.2,
    "stamina": 63.6,
    "intelligence": 73.6,
    "special": 53.1,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Sable Antelope",
    "image": "https://png.pngtree.com/png-clipart/20250528/original/pngtree-black-sable-antelope-with-horns-png-image_21085899.png",
    "attack": 15,
    "defense": 2,
    "agility": 34.1,
    "stamina": 92.9,
    "intelligence": 45.7,
    "special": 59.8,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Sailfish",
    "image": "https://png.pngtree.com/png-clipart/20250515/original/pngtree-blue-and-white-sailfish-png-image_20978677.png",
    "attack": 23.5,
    "defense": 25,
    "agility": 93.8,
    "stamina": 88.4,
    "intelligence": 32,
    "special": 55,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Salamander",
    "image": "https://static.vecteezy.com/system/resources/previews/060/068/721/non_2x/intense-beautiful-a-salamander-no-background-with-transparent-background-masterfully-captured-free-png.png",
    "attack": 0.7,
    "defense": 0,
    "agility": 0.3,
    "stamina": 33,
    "intelligence": 13,
    "special": 13,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Saltwater Crocodile",
    "image": "https://pngimg.com/d/crocodile_PNG13185.png",
    "attack": 96.2,
    "defense": 97.8,
    "agility": 12.4,
    "stamina": 52.3,
    "intelligence": 32.3,
    "special": 91,
    "description": "The largest living reptile, an ambush predator with the strongest bite force of any animal today. It dominates the water's edge, dragging prey to a watery grave."
  },
  {
    "name": "Sawfish",
    "image": "https://png.pngtree.com/png-vector/20250321/ourmid/pngtree-sawfish-fish-isolated-on-transparent-background-png-image_15814118.png",
    "attack": 23,
    "defense": 24.7,
    "agility": 14.6,
    "stamina": 47.5,
    "intelligence": 22.5,
    "special": 13.7,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Sea Lion",
    "image": "https://static.vecteezy.com/system/resources/previews/046/400/351/non_2x/sea-lion-on-transparent-background-free-png.png",
    "attack": 61.5,
    "defense": 58.6,
    "agility": 69.7,
    "stamina": 80.4,
    "intelligence": 70.7,
    "special": 65,
    "description": "A Large creature found in Coastal waters."
  },
  {
    "name": "Sea Otter",
    "image": "https://static.vecteezy.com/system/resources/thumbnails/053/775/918/small/playful-otter-holding-a-shell-for-creative-use-on-transparent-background-png.png",
    "attack": 14.9,
    "defense": 58,
    "agility": 57.3,
    "stamina": 85.9,
    "intelligence": 90.5,
    "special": 55,
    "description": "A Small creature found in Coastal waters."
  },
  {
    "name": "Seal",
    "image": "https://static.vecteezy.com/system/resources/previews/049/667/958/non_2x/adorable-baby-seal-with-transparent-background-curious-sea-pup-with-black-background-adorable-marine-animal-with-transparent-background-png.png",
    "attack": 3.6,
    "defense": 57.3,
    "agility": 53.2,
    "stamina": 82.5,
    "intelligence": 74.7,
    "special": 50,
    "description": "A Medium creature found in Coastal waters, ice."
  },
  {
    "name": "Secretary Bird",
    "image": "https://png.pngtree.com/png-clipart/20250105/original/pngtree-majestic-secretary-bird-isolated-on-transparent-background-png-image_18748927.png",
    "attack": 3.5,
    "defense": 14.1,
    "agility": 44.3,
    "stamina": 82.1,
    "intelligence": 63.9,
    "special": 17.8,
    "description": "A Medium creature found in Savannas, grasslands."
  },
  {
    "name": "Serval",
    "image": "https://png.pngtree.com/png-clipart/20250520/original/pngtree-vintage-serval-wild-cat-clipart-png-image_21044988.png",
    "attack": 3.3,
    "defense": 44.3,
    "agility": 79.3,
    "stamina": 63.1,
    "intelligence": 59.6,
    "special": 74,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Shoebill",
    "image": "https://png.pngtree.com/png-clipart/20250606/original/pngtree-shoebill-standing-exotic-bird-with-transparent-background-png-image_21131112.png",
    "attack": 3.2,
    "defense": 13.9,
    "agility": 18.2,
    "stamina": 63.7,
    "intelligence": 58.7,
    "special": 64,
    "description": "A Medium creature found in Swamps, marshes."
  },
  {
    "name": "Siberian Tiger",
    "image": "https://pngimg.com/uploads/tiger/tiger_PNG23234.png",
    "attack": 88.8,
    "defense": 64.7,
    "agility": 78.6,
    "stamina": 62.7,
    "intelligence": 59,
    "special": 82.5,
    "description": "The largest of all big cats, a solitary hunter built for power and stealth. It can take down prey much larger than itself."
  },
  {
    "name": "Skunk",
    "image": "https://static.vecteezy.com/system/resources/previews/059/952/883/non_2x/striped-skunk-animal-isolated-on-the-transparent-background-free-png.png",
    "attack": 3,
    "defense": 13.6,
    "agility": 17.9,
    "stamina": 51.8,
    "intelligence": 65.1,
    "special": 64,
    "description": "A Small creature found in Forests, grasslands, urban."
  },
  {
    "name": "Sloth",
    "image": "https://static.vecteezy.com/system/resources/previews/048/743/850/non_2x/sloth-perched-on-a-branch-all-by-itself-against-a-transparent-background-png.png",
    "attack": 2.9,
    "defense": 13.4,
    "agility": 0,
    "stamina": 17.3,
    "intelligence": 34.6,
    "special": 14.6,
    "description": "A Small creature found in Rainforests."
  },
  {
    "name": "Sloth Bear",
    "image": "https://png.pngtree.com/png-vector/20250519/ourmid/pngtree-png-sloth-bear-vintage-animal-clipart-png-image_16313847.png",
    "attack": 78.1,
    "defense": 80.5,
    "agility": 25.7,
    "stamina": 72.6,
    "intelligence": 52.9,
    "special": 80.1,
    "description": "A Medium creature found in Forests, grasslands."
  },
  {
    "name": "Snapping Turtle",
    "image": "https://png.pngtree.com/png-vector/20250619/ourmid/pngtree-snapping-turtle-isolated-on-a-transparent-background-png-image_16549683.png",
    "attack": 0.6,
    "defense": 13.1,
    "agility": 3.8,
    "stamina": 41.8,
    "intelligence": 17.4,
    "special": 42.4,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Snow Leopard",
    "image": "https://png.pngtree.com/png-clipart/20231008/original/pngtree-snow-leopard-transparent-background-png-image_13290636.png",
    "attack": 60.8,
    "defense": 64.1,
    "agility": 87.6,
    "stamina": 66.9,
    "intelligence": 65.4,
    "special": 78.5,
    "description": "The ghost of the mountains, perfectly camouflaged against rocky slopes. Its long tail provides balance for incredible leaps."
  },
  {
    "name": "Snowy Owl",
    "image": "https://png.pngtree.com/png-vector/20240326/ourmid/pngtree-snowy-owl-in-flight-colored-drawing-realistic-png-image_12204950.png",
    "attack": 33.8,
    "defense": 12.9,
    "agility": 62.8,
    "stamina": 82.6,
    "intelligence": 64.8,
    "special": 64.8,
    "description": "A Small creature found in Arctic tundra."
  },
  {
    "name": "Spectacled Bear",
    "image": "https://png.pngtree.com/png-vector/20240221/ourmid/pngtree-spectacled-bear-spectacled-bear-zoo-austria-png-image_11760603.png",
    "attack": 77.2,
    "defense": 81.3,
    "agility": 28.2,
    "stamina": 70.5,
    "intelligence": 46.5,
    "special": 78.4,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Spider Monkey",
    "image": "https://pngimg.com/d/monkey_PNG18725.png",
    "attack": 33.2,
    "defense": 43.6,
    "agility": 66.9,
    "stamina": 65.3,
    "intelligence": 87,
    "special": 68.8,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Stag Beetle",
    "image": "https://png.pngtree.com/png-clipart/20250128/original/pngtree-stag-beetle-png-image_20342640.png",
    "attack": 11.2,
    "defense": 1.8,
    "agility": 5.5,
    "stamina": 14.7,
    "intelligence": 8.7,
    "special": 58.2,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Stingray",
    "image": "https://static.vecteezy.com/system/resources/previews/024/064/362/non_2x/stingray-fish-isolated-on-a-transparent-background-free-png.png",
    "attack": 22.4,
    "defense": 24.5,
    "agility": 34.8,
    "stamina": 47.3,
    "intelligence": 22.3,
    "special": 72.5,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Stoat",
    "image": "https://static.vecteezy.com/system/resources/previews/071/094/211/non_2x/watercolor-stoat-animal-illustration-on-transparent-background-free-png.png",
    "attack": 2.7,
    "defense": 36.8,
    "agility": 29.7,
    "stamina": 62.6,
    "intelligence": 72.6,
    "special": 78.4,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Stork",
    "image": "https://png.pngtree.com/png-vector/20240809/ourmid/pngtree-abdims-stork-bird-in-migration-tracking-its-seasonal-movements-png-image_13421084.png",
    "attack": 2.6,
    "defense": 9.1,
    "agility": 17.6,
    "stamina": 81.5,
    "intelligence": 43.8,
    "special": 23.8,
    "description": "A Medium creature found in Wetlands, grasslands."
  },
  {
    "name": "Sugar Glider",
    "image": "https://png.pngtree.com/png-vector/20231018/ourmid/pngtree-sugar-glider-on-white-background-animal-png-image_10243535.png",
    "attack": 2.5,
    "defense": 12.6,
    "agility": 52.5,
    "stamina": 46.5,
    "intelligence": 61.1,
    "special": 12.3,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Sun Bear",
    "image": "https://png.pngtree.com/png-vector/20240104/ourmid/pngtree-malayan-sunbear-isolated-isolated-png-image_10889116.png",
    "attack": 76.3,
    "defense": 12.4,
    "agility": 51.1,
    "stamina": 68.1,
    "intelligence": 39.4,
    "special": 76.5,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Swan",
    "image": "https://png.pngtree.com/png-vector/20240205/ourmid/pngtree-swan-little-bird-png-image_11623895.png",
    "attack": 11.1,
    "defense": 8.8,
    "agility": 19.9,
    "stamina": 86.7,
    "intelligence": 56.6,
    "special": 36.6,
    "description": "A Medium creature found in Lakes, rivers, wetlands."
  },
  {
    "name": "Swordfish",
    "image": "https://png.pngtree.com/png-clipart/20250417/original/pngtree-swordfish-isolated-on-transparent-background-png-image_20716783.png",
    "attack": 21.8,
    "defense": 24.2,
    "agility": 92,
    "stamina": 89.1,
    "intelligence": 35.5,
    "special": 59.4,
    "description": "A Large creature found in Tropical and temperate oceans."
  },
  {
    "name": "Tapir",
    "image": "https://png.pngtree.com/png-vector/20250605/ourmid/pngtree-wildlife-tapir-for-digital-design-png-image_16462735.png",
    "attack": 2.3,
    "defense": 72.4,
    "agility": 17.4,
    "stamina": 74.3,
    "intelligence": 48.6,
    "special": 22.9,
    "description": "A Large creature found in Jungles of South America and Asia."
  },
  {
    "name": "Tarantula Hawk",
    "image": "https://texas.bugoutservice.com/wp-content/uploads/tarantula-hawk-on-white.png",
    "attack": 32.6,
    "defense": 12.1,
    "agility": 37.5,
    "stamina": 23.3,
    "intelligence": 15.7,
    "special": 89.5,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Tasmanian Devil",
    "image": "https://static.vecteezy.com/system/resources/previews/059/466/509/non_2x/a-tasmanian-devil-standing-and-looking-up-with-a-clear-isolated-background-in-a-wildlife-setting-transparent-background-free-png.png",
    "attack": 2.2,
    "defense": 11.8,
    "agility": 26.5,
    "stamina": 50.3,
    "intelligence": 37.9,
    "special": 86.5,
    "description": "A Small creature found in Forests, scrublands."
  },
  {
    "name": "Tiger Shark",
    "image": "https://png.pngtree.com/png-vector/20240315/ourmid/pngtree-tiger-shark-on-white-seawater-underwater-macropredator-png-image_11852038.png",
    "attack": 87.9,
    "defense": 63.6,
    "agility": 85.1,
    "stamina": 89.5,
    "intelligence": 37.8,
    "special": 83.5,
    "description": "A Large creature found in Tropical and temperate waters."
  },
  {
    "name": "Toucan",
    "image": "https://png.pngtree.com/png-clipart/20231007/ourmid/pngtree-keel-billed-toucan-transparent-background-png-image_10196216.png",
    "attack": 2,
    "defense": 6.1,
    "agility": 29.5,
    "stamina": 65.9,
    "intelligence": 54.6,
    "special": 31.8,
    "description": "A Small creature found in Tropical forests."
  },
  {
    "name": "Tuna",
    "image": "https://png.pngtree.com/png-vector/20231017/ourmid/pngtree-bluefin-tuna-fish-png-image_10202750.png",
    "attack": 21.2,
    "defense": 23.9,
    "agility": 81.9,
    "stamina": 86.3,
    "intelligence": 21.7,
    "special": 42.2,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Vulture",
    "image": "https://png.pngtree.com/png-clipart/20250521/original/pngtree-realistic-vulture-png-image_21049936.png",
    "attack": 32,
    "defense": 11.6,
    "agility": 36.8,
    "stamina": 81.3,
    "intelligence": 62.4,
    "special": 62.4,
    "description": "A Medium creature found in Savannas, mountains."
  },
  {
    "name": "Wallaby",
    "image": "https://www.pngmart.com/files/12/Kangaroo-Wallaby-PNG-Transparent-Image.png",
    "attack": 1.9,
    "defense": 11.3,
    "agility": 64.1,
    "stamina": 75,
    "intelligence": 50.1,
    "special": 25.1,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Walrus",
    "image": "https://pngimg.com/d/walrus_PNG111771.png",
    "attack": 1.7,
    "defense": 85.3,
    "agility": 8.3,
    "stamina": 85.5,
    "intelligence": 80.3,
    "special": 75,
    "description": "A massive marine mammal with long tusks used for hauling out onto ice and fighting. Their thick skin is nearly impervious to cold and claws."
  },
  {
    "name": "Warthog",
    "image": "https://static.vecteezy.com/system/resources/thumbnails/057/732/439/small/a-full-body-warthog-isolated-on-transparent-background-png.png",
    "attack": 31.5,
    "defense": 71.9,
    "agility": 22.7,
    "stamina": 75.5,
    "intelligence": 51,
    "special": 70,
    "description": "A Small creature found in Savannas, grasslands."
  },
  {
    "name": "Wild Boar",
    "image": "https://pngimg.com/d/boar_PNG2.png",
    "attack": 75.4,
    "defense": 71.4,
    "agility": 16.6,
    "stamina": 71.2,
    "intelligence": 42.5,
    "special": 70.5,
    "description": "A Small creature found in Forests, grasslands."
  },
  {
    "name": "Wild Horse",
    "image": "https://www.nicepng.com/png/full/85-852292_running-horse-no-background-transparent-png-image-web.png",
    "attack": 11,
    "defense": 70.9,
    "agility": 74.5,
    "stamina": 97.8,
    "intelligence": 58.1,
    "special": 74.1,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Wildebeest",
    "image": "https://png.pngtree.com/png-vector/20231224/ourmid/pngtree-wildebeest-isolated-on-white-background-wild-png-image_11221442.png",
    "attack": 60,
    "defense": 1.5,
    "agility": 40.2,
    "stamina": 93.8,
    "intelligence": 55.3,
    "special": 33,
    "description": "A Medium creature found in Savannas, grasslands."
  },
  {
    "name": "Wolverine",
    "image": "https://www.pngkey.com/png/full/97-973354_tierpark-hellabrunn-wolverine-animal-transparent.png",
    "attack": 1.6,
    "defense": 70.3,
    "agility": 29.2,
    "stamina": 63.6,
    "intelligence": 73.6,
    "special": 86,
    "description": "A stocky and muscular carnivore, known for its ferocity and strength out of proportion to its size. It can crush frozen bones."
  },
  {
    "name": "Wombat",
    "image": "https://static.vecteezy.com/system/resources/previews/053/648/166/non_2x/a-brown-and-white-wombat-on-a-transparent-background-png.png",
    "attack": 14.7,
    "defense": 11.1,
    "agility": 21.7,
    "stamina": 21.6,
    "intelligence": 43.2,
    "special": 23.2,
    "description": "A Medium creature found in Varied."
  },
  {
    "name": "Yak",
    "image": "https://assets.stickpng.com/images/5e99c00ac5844500043c6e66.png",
    "attack": 59.2,
    "defense": 69.8,
    "agility": 16.4,
    "stamina": 92,
    "intelligence": 57.5,
    "special": 73.1,
    "description": "A Large creature found in Himalayan mountains."
  },
  {
    "name": "Zebra",
    "image": "https://assets.stickpng.com/thumbs/580b57fbd9996e24bc43bd04.png",
    "attack": 1.4,
    "defense": 69.3,
    "agility": 17.1,
    "stamina": 72.7,
    "intelligence": 45.4,
    "special": 18.2,
    "description": "A Medium creature found in Savannas, grasslands."
  }
];
